#!/usr/bin/env bash
# Displays Best School 10 times 'bad luck' in 4th iteration and 'good luck' in 8th iteration
i="0"

while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
