#!/usr/bin/env bash
# Run nginx as nginx
sudo -u nginx service nginx start
sudo chmod 404 /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
pkill apache2
sudo -u nginx service nginx start
sudo chmod 666 /run/nginx.pid
sudo -u nginx service nginx start
